# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 19:38
from __future__ import unicode_literals

from django.db import migrations
import django_hstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='values',
            field=django_hstore.fields.DictionaryField(editable=False, null=True),
        ),
    ]
