export const Auth = {
    SIGN_IN: 'SIGN_IN',
    SIGN_IN_FAIL: 'SIGN_IN_FAIL',
    SIGN_UP: 'SIGN_UP',
    SIGN_UP_FAIL: 'SIGN_UP_FAIL',
    SIGN_OUT: 'SIGN_OUT',
    VERIFY_SIGNED_IN: 'VERIFY_SIGNED_IN',
	VERIFY_SIGNED_IN_ERROR: 'VERIFY_SIGNED_IN_ERROR',
    JWT_KEY: 'i18nhub_jwt'
};
